### ISSUE TITLE
Dark mode doesn't always sync with system settings 

### ISSUE THREAD

**Issue by simprecicchiani** [MSzturc/ThinkpadAssistant#24] opened 2020-06-02 08:17 UTC
When system is shut down with dark mode, ThinkpadAssistant hud keep this settings even if the system boots up in light mode (normal behaviour caused by automatic appearance setting).
<img width="1440" alt="Schermata 2020-06-02 alle 10 12 34" src="https://user-images.githubusercontent.com/46405079/83497049-321f3600-a4ba-11ea-852f-4a8dce20ce07.png">

**Comment by Sniki** [comment] 2020-06-02 08:22
> When system is shut down with dark mode, ThinkpadAssistant hud keep this settings even if the system boots up in light mode (normal behaviour caused by automatic appearance setting).
> <img alt="Schermata 2020-06-02 alle 10 12 34" width="1440" src="https://user-images.githubusercontent.com/46405079/83497049-321f3600-a4ba-11ea-852f-4a8dce20ce07.png">

This should actually be a feature request and not a bug as if im correct, Dark Mode is not implemented yet.

**Comment by MSzturc** [comment] 2020-06-02 10:00
Im not able to reproduce this error on my system. I remind a bug like this in an older version of Thinkpad Assistant. Please try to reproduce it with 1.7.2

![darkmode](https://user-images.githubusercontent.com/4275753/83507218-8b8e6180-a4c8-11ea-9422-1ba2db652380.gif)

**Comment by simprecicchiani** [comment] 2020-06-02 10:28
It behaves correctly when switching between modes. The issue is presented when shutted down and then started with different appearance mode.

**Comment by MSzturc** [comment] 2020-06-02 11:18
I've created a possible fix. Please check if this error still occurs. This fix is a bit hacky. It checks inside the rendering thread if darkmode is enabled. Normally you dont do it because it could cause shuttering in the rendering of the hud. 

[ThinkpadAssistant.app.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4716736/ThinkpadAssistant.app.zip)

**Comment by simprecicchiani** [comment] 2020-06-02 12:48
I don't really know how to test it because it happens when I shut down the computer in the evening and start it the next morning. I can provide a feedback not earlier than tomorrow.

**Comment by hexart** [comment] 2020-06-03 01:01
> I don't really know how to test it because it happens when I shut down the computer in the evening and start it the next morning. I can provide a feedback not earlier than tomorrow.

I've just experienced the same issue this morning as @simprecicchiani described. It reproduces only in the morning when you are using automantic system appearance.

**Comment by hexart** [comment] 2020-06-03 01:02
> I've created a possible fix. Please check if this error still occurs. This fix is a bit hacky. It checks inside the rendering thread if darkmode is enabled. Normally you dont do it because it could cause shuttering in the rendering of the hud.
> 
> [ThinkpadAssistant.app.zip](https://github.com/MSzturc/ThinkpadAssistant/files/4716736/ThinkpadAssistant.app.zip)

I haven't tried this one, I'll test it and report back next day.

**Comment by Sniki** [comment] 2020-06-05 18:27
i agree as well, the problem is present, last time i used it was night time and dark mode was on automatically and the HUD was dark as well which is fine, today (daytime) system was set to white/light theme automatically because it was daytime and when i pressed the backlight key, i noticed the HUD was still dark instead of white as the theme is.

**Comment by joshuaseltzer** [comment] 2020-06-10 22:47
Would you be able to implement a method (maybe in your App Delegate or something) that checks for sleep/wake to check the status of dark mode?  I'm thinking you could watch for this notification:
https://developer.apple.com/documentation/appkit/nsworkspacedidwakenotification

And then you can determine dark mode using a method described in one of the answers here, using NSAppearance:
https://stackoverflow.com/questions/51672124/how-can-dark-mode-be-detected-on-macos-10-14

(I'm an iOS developer with strong Objective-C knowledge -- very little Swift experience -- so disregard this comment if I'm completely off base.)

**Comment by MSzturc** [comment] 2020-06-11 11:47
Thx for the hint! As recommended by @joshuaseltzer I enhanced the code that detects which theme is currently active. This bug is fixed with v1.7.3

**Comment by joshuaseltzer** [comment] 2020-06-11 12:24
Glad I was able to provide some useful hints! If I knew Swift I would have tried it myself and submitted a PR.

**Comment by MSzturc** [comment] 2020-06-12 16:15
Tested today in the morning & it worked for me as intended!

**Closed by MSzturc** 2020-06-12 16:15 UTC

**Comment by Sniki** [comment] 2020-06-12 20:42
> Tested today in the morning & it worked for me as intended!

Tested today as well, just a few minutes before Dark mode will turn on automatically, as soon as it turned on while using the laptop, i tested and it's working perfect.

Thank you @joshuaseltzer @MSzturc
